# Generated by Django 5.2.13 on 2026-04-15 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_auto_20260412_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingtask',
            name='log',
        ),
        migrations.RemoveField(
            model_name='pendingtask',
            name='user',
        ),
        migrations.DeleteModel(
            name='DailyLog',
        ),
        migrations.DeleteModel(
            name='PendingTask',
        ),
    ]
