# Generated by Django 5.2.13 on 2026-05-01 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='date',
            field=models.DateField(),
        ),
    ]
